### ISSUE TITLE
export types 

### ISSUE THREAD

**Issue by pascalkania** [Borodin/typescript-telegram-bot-api#13]
Hey,

thank you for your effort. for strictly typing and usage of the TelegramBot, it would be great if the response types like Promise<User> could be reused.

i getting an error because, User ist declared but not exported

i also can create a pr, but i dont know if this is wanted.

**Comment by Borodin** [comment]
The response types are exported; you can use them like this:

```typescript
import { MethodReturn } from "typescript-telegram-bot-api";
Promise<MethodReturn<'getMe'>>
```
or

```typescript
import * as TGTypes from 'typescript-telegram-bot-api/dist/types';
Promise<TGTypes.User>
```

But if that's not enough for you, I would be very happy to receive your PR.

**Comment by Borodin** [comment]
@pascalkania Did my answer help you?

**Comment by pascalkania** [comment]
![image](https://github.com/user-attachments/assets/c857b1f6-0b30-4bd1-9a93-4e4968faa9f9)

I wanted to import users directly from `typescript-telegram-bot-api `

but with `import { User } from 'typescript-telegram-bot-api/dist/types';` it works now. 

thanks for the help.
